---
permalink: recover/recovery-deployment.html 
sidebar: sidebar 
keywords:  
summary: Wenn Sie Ihre ONTAP-Tools für die VMware vSphere-Einrichtung verlieren, aber Ihre ONTAP funktionieren lassen, können Sie ONTAP-Tools für die VMware vSphere-Einrichtung mithilfe des ONTAP wiederherstellen. Wenn Sie das Setup verlieren, fahren Sie das Setup ordnungsgemäß herunter. 
---
= Stellen Sie Ihre ONTAP Tools für die Einrichtung von VMware vSphere wieder her
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie Ihre ONTAP Tools für die VMware vSphere-Einrichtung verlieren, können Sie die ONTAP Tools für die VMware vSphere-Einrichtung unter Verwendung der in den ONTAP Volume-Daten verfügbaren Daten wiederherstellen. Wenn Sie das Setup verlieren, fahren Sie das Setup ordnungsgemäß herunter.


NOTE: Sie können Ihre ONTAP Tools für die VMware vSphere-Einrichtung nicht wiederherstellen, wenn Probleme mit vCenter Server- oder ONTAP-Datenmanagement-Software auftreten.

*Schritte*

. Melden Sie sich beim vSphere-Server an.
. Navigieren Sie zum Ressourcenpool, den Sie erstellt haben, oder zum Node-Cluster oder zum Host, auf dem Sie die OVA bereitstellen möchten.
. Klicken Sie mit der rechten Maustaste auf den gewünschten Speicherort und wählen Sie *OVF-Vorlage bereitstellen*.
. Wählen Sie die OVA-Datei entweder über die URL für die _.ova_-Datei aus, oder navigieren Sie zu dem Ordner, in dem die _.ova_-Datei gespeichert ist, und klicken Sie dann auf *Weiter*.
+

NOTE: Sie sollten denselben OVA-Build verwenden, den Sie für die Installation der Wiederherstellungseinrichtung verwendet haben.

. Wählen Sie einen Namen und Ordner für die virtuelle Maschine aus und wählen Sie *Weiter*.
. Wählen Sie den Host aus und wählen Sie *Weiter*.
. Überprüfen Sie die Zusammenfassung der Vorlage und wählen Sie *Weiter*.
. Lesen und akzeptieren Sie die Lizenzvereinbarung und wählen Sie *Weiter*.
. Wählen Sie im Fenster *Konfiguration* die Option *Wiederherstellung*.
. Wählen Sie im Fenster *Speicher auswählen* den Speicher für die Konfigurationen und Festplattendateien aus.
. Wählen Sie im Fenster *Netzwerke auswählen* für jedes Quellnetzwerk ein Zielnetzwerk aus.
+

NOTE: Sie müssen die IP-Adresse des Load Balancer und die IP-Adresse des Kubernetes API Servers beibehalten. Sie können die Node-IP-Adresse ändern oder dieselbe IP-Adresse beibehalten.

. Geben Sie im Fenster *Vorlage anpassen* die erforderlichen Details ein und klicken Sie auf *Weiter*
+

NOTE: Wenn der SVM-Bereich aktiviert ist, sollte die SVM-Unterstützung mit der Management-IP-Adresse bereits aktiviert sein.

. Überprüfen Sie die Details im Fenster *Ready to Complete*, wählen Sie *Finish*.
+
Wenn die Bereitstellungsaufgabe erstellt wird, wird der Fortschritt in der vSphere-Taskleiste angezeigt.

. Schalten Sie die VM nach Abschluss der Aufgabe ein.
+
Die Installation beginnt. Sie können den Installationsfortschritt in der Web-Konsole der VM verfolgen. Im Rahmen der Installation werden Node-Konfigurationen validiert. Die Eingaben, die unter verschiedenen Abschnitten unter der Vorlage „Anpassen“ im OVF-Formular bereitgestellt werden, werden validiert. Bei Unstimmigkeiten werden Sie in einem Dialogfeld aufgefordert, Korrekturmaßnahmen zu ergreifen.

. Nehmen Sie die erforderlichen Änderungen in der Dialogaufforderung vor. Verwenden Sie die Tabulatortaste, um durch das Bedienfeld zu navigieren, und wählen Sie *OK*.
+
Die angegebenen Werte werden erneut validiert. Mit den ONTAP-Tools für VMware vSphere können Sie drei Versuche durchführen, ungültige Werte zu korrigieren. Wenn Sie Probleme nach drei Versuchen nicht beheben können, wird die Produktinstallation angehalten, und Sie werden aufgefordert, die Installation auf einer neuen VM zu versuchen.



Nach der erfolgreichen Installation zeigt die Webkonsole den Status der ONTAP Tools für VMware vSphere an.

Nach erfolgreicher Installation sollten Sie die Hardwareanforderungen gemäß den Richtlinien auf der Seite manuell bearbeiten link:../deploy/prerequisites.html["Voraussetzungen für die Bereitstellung von ONTAP-Tools für VMware vSphere"] .
