---
section: deploy
title: Implementieren Sie ONTAP-Tools für VMware vSphere
entries:
- title: Voraussetzungen
  url: "/deploy/prerequisites.html"
- title: Implementierung von ONTAP Tools
  url: "/deploy/ontap-tools-deployment.html"
- title: Fehlercodes für die Bereitstellung
  url: "/deploy/deployment-error-codes.html"
