---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: Sie sollten Schutzgruppen erstellen, um eine Gruppe virtueller Maschinen am geschützten Standort zu schützen. 
---
= Konfigurieren Sie Schutzgruppen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten Schutzgruppen erstellen, um eine Gruppe virtueller Maschinen am geschützten Standort zu schützen.

*Was Sie brauchen*

Stellen Sie sicher, dass die Quell- und Zielstandorte für Folgendes konfiguriert sind:

* Dieselbe Version von VMware Live Site Recovery ist installiert
* Virtual Machines
* Gepaarte geschützte Standorte und Recovery-Standorte
* Quell- und Ziel-Datastores sollten auf den jeweiligen Sites gemountet werden


*Schritte*

. Melden Sie sich bei vCenter Server an und klicken Sie dann auf *Site Recovery* > *Protection Groups*.
. Klicken Sie im Fensterbereich *Schutzgruppen* auf *Neu*.
. Geben Sie einen Namen und eine Beschreibung für die Schutzgruppe, Richtung und klicken Sie auf *Weiter*.
. Wählen Sie im Feld *Typ* die Option *Typ Feld...* als Datastore-Gruppen (Array-basierte Replikation) für NFS- und VMFS-Datastore aus. Die Fehlerdomäne ist nichts anderes als SVMs mit aktivierter Replizierung. Es werden die SVMs angezeigt, für die lediglich Peering implementiert ist und keine Probleme vorhanden sind.
. Wählen Sie auf der Registerkarte Replikationsgruppen entweder das aktivierte Array-Paar oder die Replikationsgruppen aus, für die die virtuelle Maschine konfiguriert ist, und klicken Sie dann auf *Weiter*.
+
Alle virtuellen Maschinen auf der Replikationsgruppe werden der Schutzgruppe hinzugefügt.

. Wählen Sie entweder den vorhandenen Wiederherstellungsplan aus oder erstellen Sie einen neuen Plan, indem Sie auf *zu neuem Wiederherstellungsplan hinzufügen* klicken.
. Überprüfen Sie auf der Registerkarte bereit zum Abschließen die Details der von Ihnen erstellten Schutzgruppe, und klicken Sie dann auf *Fertig stellen*.

