---
permalink: protect/enable-storage-replication-adapter.html 
sidebar: sidebar 
keywords:  
summary: ONTAP Tools für VMware vSphere bieten die Option zur Aktivierung der SRA-Funktionen zur Konfiguration der Disaster Recovery. 
---
= Aktivieren Sie SRA, um Datastores zu sichern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Tools für VMware vSphere bieten die Option zur Aktivierung der SRA-Funktionen zur Konfiguration der Disaster Recovery.

*Was Sie brauchen*

* Sie sollten Ihre vCenter Server-Instanz eingerichtet und den ESXi-Host konfiguriert haben.
* Sie hätten ONTAP Tools bereitstellen sollen.
* Sie sollten die SRA Adapter- `.tar.gz`Datei von der heruntergeladen haben https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp Support-Website"^].


*Schritte*

. Melden Sie sich über die URL: An der VMware Live Site Recovery Appliance Management Interface an `\https://:<srm_ip>:5480`, und wechseln Sie dann zu Storage Replication Adapters in VMware Live Site Recovery Appliance Management Interface.
. Wählen Sie *New Adapter*.
. Laden Sie das Installationsprogramm _.tar.gz_ für das SRA-Plug-in auf VMware Live Site Recovery hoch.
. Überprüfen Sie die Adapter erneut, um sicherzustellen, dass die Details auf der Seite VMware Live Site Recovery Storage Replication Adapters aktualisiert werden.

