---
permalink: protect/map-network.html 
sidebar: sidebar 
keywords:  
summary: Sie sollten Ihre Netzwerke am geschützten Standort und am Wiederherstellungsstandort zuordnen, um die Kommunikation zwischen ihnen zu ermöglichen. 
---
= Konfigurieren Sie die Netzwerkzuordnungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie sollten Ihre Ressourcenzuordnungen wie VM-Netzwerke, ESXi-Hosts und Ordner an beiden Standorten konfigurieren, um die Zuordnung jeder Ressource vom geschützten Standort zur entsprechenden Ressource am Recovery-Standort zu ermöglichen.

Sie sollten die folgenden Ressourcenkonfigurationen abschließen:

* Netzwerkzuordnungen
* Ordnerzuordnungen
* Ressourcen-Zuordnungen
* Platzhalter-Datenspeicher


*Was Sie brauchen*

Sie sollten die geschützten und Recovery-Standorte verbunden haben.

*Schritte*

. Melden Sie sich am vCenter Server an und klicken Sie auf *Site Recovery* > *Sites*.
. Wählen Sie Ihre geschützte Site aus und klicken Sie auf *Verwalten*.
. Wählen Sie auf der Registerkarte Verwalten die Option *Netzwerkzuordnungen* aus.
. Klicken Sie auf *Neu*, um ein neues Netzwerk-Mapping zu erstellen.
+
Der Assistent „Netzwerkzuordnung erstellen“ wird angezeigt.

. Führen Sie im Assistenten „Netzwerkzuordnung erstellen“ folgende Schritte aus:
+
.. Wählen Sie *Zuordnungen für Netzwerke mit übereinstimmenden Namen automatisch vorbereiten* aus und klicken Sie auf *Weiter*.
.. Wählen Sie die gewünschten Rechenzentrumsobjekte für die geschützten und Recovery-Standorte aus und klicken Sie auf *Zuordnungen hinzufügen*.
.. Klicken Sie auf *Weiter*, nachdem Zuordnungen erfolgreich erstellt wurden.
.. Wählen Sie das zuvor verwendete Objekt aus, um eine umgekehrte Zuordnung zu erstellen, und klicken Sie dann auf *Fertig stellen*.




*Ergebnis*

Auf der Seite Netzwerkzuordnungen werden die geschützten Standortressourcen und die Ressourcen des Recovery-Standorts angezeigt. Sie können die gleichen Schritte für andere Netzwerke in Ihrer Umgebung befolgen.
