---
permalink: configure/install-nfs-vaai-plug-in.html 
sidebar: sidebar 
keywords:  
summary: 'Sie können das NetApp NFS-Plug-in für VMware vStorage APIs for Array Integration \(VAAI\) mit den ONTAP Tools für VMware vSphere installieren.' 
---
= Installieren Sie das NFS VAAI Plug-in
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das NetApp-NFS-Plug-in für vSphere-APIs für die Array-Integration (VAAI) mithilfe von ONTAP-Tools für VMware vSphere installieren.

*Was Sie brauchen*

* Sie sollten das Installationspaket für das NFS-Plugin für VAAI (`.vib`von der NetApp-Support-Website heruntergeladen haben. https://mysupport.netapp.com/site/products/all/details/nfsplugin-vmware-vaai/downloads-tab["NetApp NFS Plug-in für VMware VAAI"]
* Sie sollten den aktuellen ESXi-Host 7.0U3-Patch als Mindestversion und ONTAP 9.12.1Px (neueste P-Version) 9.13.1Px, 9.14.1Px oder höher installiert haben.
* Sie sollten den ESXi-Host eingeschaltet und einen NFS-Datastore gemountet haben.
* Sie sollten die Werte der `DataMover.HardwareAcceleratedMove` , `DataMover.HardwareAcceleratedInit` und `VMFS3.HardwareAcceleratedLocking` Host-Einstellungen auf „`1`“ gesetzt haben.
+
Diese Werte werden automatisch auf dem ESXi-Host gesetzt, wenn das Dialogfeld Empfohlene Einstellungen aktualisiert wird.

* Sie sollten die vstorage-Option auf der Storage Virtual Machine (SVM) mit dem `vserver nfs modify -vserver vserver_name -vstorage enabled` Befehl aktiviert haben.
* Sie sollten ESXi 7.0U3 oder höher verwenden, wenn Sie das NetApp NFS VAAI Plug-in 2.0 verwenden.
* Sie sollten die neuesten vSphere 7.0U3-Patch-Versionen haben, da vSphere 6.5 veraltet ist.
* VSphere 8.x wird mit dem NetApp NFS VAAI Plug-in 2.0.1(Build 16) unterstützt.


*Schritte*

. Klicken Sie auf der Startseite von ONTAP Tools für VMware vSphere auf *Einstellungen*.
. Klicken Sie auf die Registerkarte * NFS VAAI Tools*.
. Wenn das VAAI-Plug-in auf vCenter Server hochgeladen wird, wählen Sie im Bereich *existing Version* *Change* aus. Wenn kein VAAI-Plug-in auf den vCenter-Server hochgeladen wird, klicken Sie auf die Schaltfläche *Upload*.
. Durchsuchen Sie die `.vib` Datei, wählen Sie sie aus und klicken Sie auf *Hochladen*, um die Datei in ONTAP-Tools hochzuladen.
. Klicken Sie auf *auf ESXI-Host installieren*, wählen Sie den ESXi-Host aus, auf dem Sie das NFS VAAI-Plug-in installieren möchten, und klicken Sie dann auf *Installieren*.
+
Es werden nur die ESXi-Hosts angezeigt, die für die Plug-in-Installation geeignet sind. Befolgen Sie die Anweisungen auf dem Bildschirm, um die Installation abzuschließen. Sie können den Installationsfortschritt im Abschnitt Letzte Aufgaben von vSphere Web Client überwachen.

. Sie sollten den ESXi-Host nach Abschluss der Installation manuell neu starten.
+
Wenn der VMware-Administrator den ESXi-Host neu startet, erkennen die ONTAP-Tools für VMware vSphere automatisch das NFS VAAI-Plug-in. Sie müssen keine weiteren Schritte zum Aktivieren des Plug-ins ausführen.





=== Konfigurieren Sie die richtigen NFS-Exportrichtlinien für den VAAI Copy-Offload

Wenn Sie VAAI in einer NFS-Umgebung konfigurieren, sollten die Regeln für Exportrichtlinien unter Berücksichtigung der folgenden Anforderungen konfiguriert werden:

* Das entsprechende Volume muss die NFSv4-Aufrufe zulassen.
* Der Root-Benutzer sollte als Root bleiben und NFSv4 in allen übergeordneten Volumes der Verbindung zugelassen werden.
* Die Option für VAAI Support muss auf dem jeweiligen NFS Server eingestellt werden.


Weitere Informationen zum Verfahren finden Sie im https://kb.netapp.com/on-prem/ontap/DM/VAAI/VAAI-KBs/Configure_the_correct_NFS_export_policies_for_VAAI_copy_offload["Konfigurieren Sie die richtigen NFS-Exportrichtlinien für den VAAI Copy-Offload"] KB-Artikel.
