---
permalink: manage/mount-datastores-on-host.html 
sidebar: sidebar 
keywords:  
summary: Durch das Mounten eines Datenspeichers können zusätzliche Hosts auf den Speicher zugreifen. Nachdem Sie die Hosts der VMware Umgebung hinzugefügt haben, können Sie den Datastore auf den zusätzlichen Hosts einbinden. 
---
= Mounten von NFS- und VMFS-Datastores
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Durch das Mounten eines Datenspeichers können zusätzliche Hosts (NFS/VMFS) auf den Speicher zugreifen. Nachdem Sie die Hosts der VMware Umgebung hinzugefügt haben, können Sie den Datastore auf den zusätzlichen Hosts einbinden.

* Einige der Rechtsklick-Aktionen sind abhängig von den vSphere-Client-Versionen und dem ausgewählten Datastore-Typ deaktiviert oder nicht verfügbar. Wenn Sie vSphere Client 8.0 oder höher verwenden, sind einige der Optionen mit der rechten Maustaste ausgeblendet.
* Von vSphere 7.0U3 bis vSphere 8.0, obwohl die Optionen angezeigt werden, wird die Aktion deaktiviert.
* Mount Datastore ist deaktiviert, wenn der Host-Cluster mit einheitlichen Konfigurationen geschützt ist.


*Schritte*

. Klicken Sie auf der vSphere Client-Startseite auf *Hosts und Cluster*.
. Wählen Sie im Navigationsbereich das Rechenzentrum aus, das den Host enthält.
. Wiederholen Sie Schritt 2 für weitere Hosts.
. Um NFS/VMFS-Datastores auf dem Host oder Host-Cluster zu mounten, klicken Sie mit der rechten Maustaste darauf und wählen Sie *NetApp ONTAP Tools* > *Mount Datastores* aus.
. Wählen Sie die Datenspeicher aus, die Sie mounten möchten, und klicken Sie auf *Mount*.


Sie können den Fortschritt im Fenster Letzte Aufgabe verfolgen.
